# This workflow will build sdist and upload a Python Package using Twine when a release is created.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build package
      run: python setup.py sdist
    - name: Publish package
    - run: twine upload dist/*
